name: simp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-220.0.dev <4.0.0'

dependencies:
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.2
  firebase_database: ^10.4.11
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  mailer: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/POOL.jpg
    - lib/assets/images/POOL2.jpg
    - lib/assets/images/Piscina.jpg
    - lib/assets/images/facebook.png
    - lib/assets/images/Google.png
    - lib/assets/images/Logo.png
    - lib/assets/images/fondopi.jpeg
    - android/app/src/main/res/mipmap-hdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

