// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMOtK8rd5gzT8nrWYn7vSc6sW3gmCy2Lg',
    appId: '1:601426770326:android:44e021ddfa6db989fe45b7',
    messagingSenderId: '601426770326',
    projectId: 'simp-9f6ba',
    databaseURL: 'https://simp-9f6ba-default-rtdb.firebaseio.com',
    storageBucket: 'simp-9f6ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeFPAyxRV9IcYm7jg1r7KNjoizx4Xigeo',
    appId: '1:601426770326:ios:c28e6cb8103a49dcfe45b7',
    messagingSenderId: '601426770326',
    projectId: 'simp-9f6ba',
    databaseURL: 'https://simp-9f6ba-default-rtdb.firebaseio.com',
    storageBucket: 'simp-9f6ba.appspot.com',
    iosClientId: '601426770326-a0fdi5345kanm64ftqto6bho272vr10h.apps.googleusercontent.com',
    iosBundleId: 'com.example.simp',
  );
}
